### ISSUE TITLE
Can not compile https://github.com/googledrive/android-quickstart sample project 

### ISSUE THREAD

**Issue by Philicoe** [googledrive/android-demos#10]
Hi There,
I need help with importing / running this Android google drive quick start sample project in Eclipse.
https://github.com/googledrive/android-quickstart sample project 
The code i downloaded was from this link below:
https://github.com/googledrive/android-demos/archive/master.zip

My problem: It does not compile.
Whether I create a ne project with the same class / package name, or After i import the project as is using the Eclipse import faclity, the project does not compile.
I get like 612 errors.
All of them looks like eclipse can not find certain class paths or something similar.
Example errors:
Description Resource Path Location Type
AndroidManifest.xml file missing! HomeActivity Unknown Android Packaging Problem _ BUT YET the file is present
Description Resource Path Location Type
ChangeEvent cannot be resolved to a type ListenChangeEventsForFilesActivity.java /HomeActivity/src/com/google/android/gms/drive/sample/demo/events line 116 Java Problem
and many more like that.
I tried cleaning the project, but not working

Can some one PLEASE PLEASE HELP?

**Comment by kroikie** [comment]
Closing, please reopen if still an issue.
