### ISSUE TITLE
Not updating my MetadataBufferResult when i query concurrently 

### ISSUE THREAD

**Issue by naveenkumarn2** [googledrive/android-demos#12]
If i request a query for the child of root folder it will return the some values but i also checking it's a trash bin value or not. but it's returning non trash values but i am not having anything in my drive root folder it's updating my buffer result after some hours later how can i get the current existing folders or files in the drive root folder

**Comment by kroikie** [comment]
Sounds like you need to listen for change events, but I'm closing, please reopen if you still think there is an issue.
