### ISSUE TITLE
issue in open folderpicker in fragment

### ISSUE THREAD

**Issue by Slake07** [googledrive/android-demos#28]
startIntentSenderForResult(
                    intentSender, REQUEST_CODE_OPENER, new Intent(), 0, 0, 0);

above method not working in fragment. it working fine in activity. help me out to solve it.

**Comment by kroikie** [comment]
You should be able to handle the result in onActivityResult in the fragment. If the activity is handling the REQUEST_CODE_OPENER and not calling super or calling fragment.onActivityResult then the call may get stuck in the activity and never get to the fragment.

**Comment by kroikie** [comment]
Closing this issue, please open another if still exists.

**Comment by niranjansheshadri** [comment]
@kroikie I am having same issue which is mentioned in the comment above,

startIntentSenderForResult(intentSender, REQUEST_CODE_OPENER, null, 0, 0, 0);

I am even handling the onActivityResult in my Fragment and even calling super.onActivityResult. It is working fine in activity. help me to solve it.
