### ISSUE TITLE
Sync request rate limit exceeded. Why?

### ISSUE THREAD

**Issue by rulogarcillan** [googledrive/android-demos#30]
only connect when performing a new task manually synchronize data because I've had problems but I am getting an error message when syncing "Sync request rate limit exceeded"
How do I can fix it? 

        @Override
         public void onConnected(Bundle bundle) {
            dialog.setMessage(getResources().getString(R.string.dialogBackup2));

            Drive.DriveApi.requestSync(mGoogleApiClient)
                    .setResultCallback(new ResultCallback<Status>() {
                        @Override
                        public void onResult(Status result) {

                            if (!result.isSuccess()) {
                                // Sync not ok
                                showMessage(result.getStatusMessage().toString());
                                //showMessage(getResources().getString(R.string.errBackup1));
                                dialog.dismiss();
                                return;
                            }
                            dialog.setMessage(getResources().getString(R.string.dialogBackup3));
                            Query query = new Query.Builder().build();
                            Drive.DriveApi.query(getGoogleApiClient(), query)
                                    .setResultCallback(compruebaFolder);
                            dialog.dismiss();
                        }
                    });
        }

**Comment by kroikie** [comment]
Generally you would get this error when you call requestSync too often. When you get the error you should exponentially back off and eventually it will succeed. Why are you calling requestSync here?

**Comment by kroikie** [comment]
Closing cause of no response.
