### ISSUE TITLE
Pickfolder picker issue

### ISSUE THREAD

**Issue by Slake07** [googledrive/android-demos#31]
when i open pickfolder picker and create new folder using that and then select that new folder, it throws nullpointerexception on driveid.

**Comment by nabinkhadka** [comment]
Because the newly created folder doesn't get committed. It takes some time.

**Comment by Slake07** [comment]
what should i do? because i need that id after created on select.

**Comment by nabinkhadka** [comment]
May be check for null value or use a try catch block to show the picker again and display a toast to ask to pick again. I have done similar thing in one of my project

**Comment by Slake07** [comment]
okey thanks. and can we close activity on click of cancel button? becuase
it opens again whenever i click on cancel button or back button..

**Comment by nabinkhadka** [comment]
Put "finish()" after "startIntentSenderForResult". I am not sure if that will solve it but give it a try

**Comment by kroikie** [comment]
Hi @Slake07 the DriveId should be available in onActivityResult. Could you confirm if this issue is still occurring?

**Comment by kroikie** [comment]
Closing due to no response. If still occurring please open a new issue.
