### ISSUE TITLE
intent data is null in onactivityresult of PickFolderWithOpenerActivity class when select account in google android

### ISSUE THREAD

**Issue by Slake07** [googledrive/android-demos#32]
I got below error when i select account from account chooser dialog:

04-17 18:42:29.912: E/AndroidRuntime(20652): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.drive.testdemo/com.drive.testdemo.PickFolderWithOpenerActivity}: java.lang.NullPointerException
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3432)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3475)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at android.app.ActivityThread.access$1300(ActivityThread.java:139)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at android.os.Looper.loop(Looper.java:136)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at android.app.ActivityThread.main(ActivityThread.java:5086)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at java.lang.reflect.Method.invoke(Method.java:515)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at dalvik.system.NativeStart.main(Native Method)
04-17 18:42:29.912: E/AndroidRuntime(20652): Caused by: java.lang.NullPointerException
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at com.drive.testdemo.PickFolderWithOpenerActivity.onActivityResult(PickFolderWithOpenerActivity.java:67)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at android.app.Activity.dispatchActivityResult(Activity.java:5446)
04-17 18:42:29.912: E/AndroidRuntime(20652): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3428)

**Comment by nabinkhadka** [comment]
Got the solution yet?

**Comment by Slake07** [comment]
yes solved..
