### ISSUE TITLE
super.onCreate

### ISSUE THREAD

**Issue by CoolMind** [googledrive/android-demos#34]
Hello!
In https://github.com/googledrive/android-demos/blob/master/src/com/google/android/gms/drive/sample/demo/ListFilesInFolderActivity.java it is written:

    @Override
    public void onConnected(Bundle connectionHint) {
        super.onCreate(connectionHint);
        setContentView(R.layout.activity_listfiles);

I think it's a slip of the pen (maybe copy & paste from https://github.com/googledrive/android-demos/blob/master/src/com/google/android/gms/drive/sample/demo/ListFilesActivity.java). Maybe delete a line with super.onCreate?

**Comment by kroikie** [comment]
Thanks @CoolMind

**Comment by CoolMind** [comment]
@kroikie: glad to hear you again.

**Comment by kroikie** [comment]
Updated to include onCreate and onConnected overrides.

**Comment by CoolMind** [comment]
Thanks, @kroikie!
Could you, please, also edit a contents of some other files like https://github.com/googledrive/android-demos/blob/master/src/com/google/android/gms/drive/sample/demo/QueryFilesInFolderActivity.java.

**Comment by kroikie** [comment]
Done.
