### ISSUE TITLE
Invalid parent folder

### ISSUE THREAD

**Issue by Slake07** [googledrive/android-demos#35]
i am creating one folder using drive API from one device. now i am trying to create file inside that folder using other device but i cant create it. i am getting invalid parent folder error. please help me with this major issue.

**Comment by seanpjanson** [comment]
If the other device is running the app authorized under the same PackageName/SHA1 (the same app), you should be able to access the folder using it's ResourceID ( not the DriveID ! ) on the other device. Or find the folder using a search on any of the metadata fields ( i.e. title ). See http://stackoverflow.com/questions/29030110/cannot-get-folderid-that-i-just-created-on-google-drive/29049474#29049474

**Comment by Slake07** [comment]
yes, i am using same application on other device. but i am creating folder so that i cant get resourceID thats why i am using driveID.. is this main reason?

**Comment by seanpjanson** [comment]
yes, DriveID is valid on a particular instance on GooPlaySvcs (i.e. one device). See the SO link above. You can get the ResourceID from the DriveID with some delay (after GooPlaySvcs commit the changes). Search SO for:    "'[google-drive-android-api] DriveID ResourceID" (aka http://stackoverflow.com/search?q=%5Bgoogle-drive-android-api%5D+DriveID+ResourceID)

**Comment by Slake07** [comment]
Thank you so much. can you help me how can i forcely commit changes.?

**Comment by kroikie** [comment]
Have a look at [completion events][1]

[1]: https://developers.google.com/drive/android/completion

**Comment by robsmall** [comment]
Hey, it looks like there is a similar issue documented well here: http://techqa.info/programming/question/33248420/invalid-parent-folder-error-for-appfolder-in-drive-api

Are there any plans to solve this issue?

**Comment by or-dvir** [comment]
i am having a similar (but not exactly the same) problem.
please take a look at #72
