### ISSUE TITLE
how to get resource id of pro grammatically created folder? 

### ISSUE THREAD

**Issue by Slake07** [googledrive/android-demos#36]
i want to store resource id of dynamically created folder in google drive using API for creating file inside it. how can i get that? i already tried below code but it always returns null.

Log.e("UPLO", "RES ID: " + folder.getDriveId().getResourceId());

i also tried waiting for 5 seconds and then fetch resourceID from stored driveid of folder but still getting null.

**Comment by kroikie** [comment]
The resource id is not available until the created folder is synced to the server. Completion events can be used to let you know when syncing to the server is complete. Check [android-conflict][1] for an example of using completion events and see the documentation [here][2].

[1]: https://github.com/googledrive/android-conflict
[2]: https://developers.google.com/drive/android/completion
