### ISSUE TITLE
Error signing the specified account

### ISSUE THREAD

**Issue by madankb** [googledrive/android-demos#37]
I imported the app to Android studio and executed in my mobile. But I am getting "Error signing into specified account" when I try to do any operation. But there is no issue with my credentials, can you please help me to solve this issue?.

**Comment by seanpjanson** [comment]
This error definitely indicates a problem with your credentials.  [Try this](http://stackoverflow.com/questions/31252524/android-drive-googleplayservicesutil-the-specified-account-could-not-be-signed/31525197#31525197)

**Comment by kroikie** [comment]
@madankb are you still having issues getting this sample to work?

**Comment by kroikie** [comment]
Closing, please create new issue if it still exists.
