### ISSUE TITLE
Reason for extending AsyncTask with ApiClientAsyncTask ?

### ISSUE THREAD

**Issue by seanpjanson** [googledrive/android-demos#38]
I've noticed that the AsyncTask has been extended with ApiClientAsyncTask [on Feb 17,2014](https://github.com/googledrive/android-demos/commits/master/src/com/google/android/gms/drive/sample/demo/ApiClientAsyncTask.java). There is no documentation or reason given for this extension and I can't figure out  why is that necessary. Can the author of this change ('rakyll)' enlighten me on this issue?

**Comment by nabinkhadka** [comment]
Where? @seanpjanson Thank you

**Comment by seanpjanson** [comment]
[here](https://github.com/googledrive/android-demos/blob/master/src/com/google/android/gms/drive/sample/demo/ApiClientAsyncTask.java)

**Comment by kroikie** [comment]
Looks like a convenience change to me. Since all of the AsyncTasks in the sample are doing some interaction with GoogleApiClient. @seanpjanson is there something about this that concerns you?

**Comment by seanpjanson** [comment]
No, just an unexplained code. Nothing that a sentence or two wouldn't fix.

**Comment by kroikie** [comment]
Cool, I think it was mainly to reduce repetition of GoogleApiClient similar to what happens with BaseDemoActivity.
