### ISSUE TITLE
Doesn't move beyond choose account dialog

### ISSUE THREAD

**Issue by pmk2429** [googledrive/android-demos#45]
App runs and installs successfully on my Nexus 5 device. Android v 6.0.1. I have multiple accounts linked in the same device. As a result, when the dialog box pops up for selecting account. When the account is chosen, it recalls the same dialog box over and over again. The Android device back button doesnt work either.
Any fix?

**Comment by tomatosmoothie** [comment]
^ Ditto!

**Comment by pmk2429** [comment]
I got a fix by authenticating the app on Google Dev console.
