### ISSUE TITLE
getMetadataBuffer() memory leak?

### ISSUE THREAD

**Issue by seanpjanson** [googledrive/android-demos#5]
1/  am not sure about this, but I noticed when using getMetadataBuffer() in my implementation, it creates a memory leak without using 'close()' on the buffer. I was searching the DEMO code  for the same sequence but did not find 'close()' there. Do you see memleaks there?

2/ In README.MD, I don't see a reference to RetrieveContentsWithProgressDialogActivity  (mentioned in 'https://developers.google.com/drive/android/files' and present in the code set). Probably by-design and a non-issue.

Sorry, for being obnoxious, I know these are minor issues. I'm trying to point out roadblocks I run into, most of them probably caused more by my lack of knowledge/ignorance.

**Comment by kroikie** [comment]
Closing, please reopen if this is still an issue.
