### ISSUE TITLE
Location of download file

### ISSUE THREAD

**Issue by kinDSa** [googledrive/android-demos#56]
I am using RetrieveContentsWithProgressDialogActivity to download file. Download progress is successfully show and after progress complete it show toast message "File contents opened".
But I not found download file in my device.
Let me know that where download file is store.

**Comment by ivanove** [comment]
Hi,
Can you show me how to download file using this api demo cause, it's displaying files but it's deactivated, I can't click on it to run download.

Thank's

**Comment by seanpjanson** [comment]
Sorry I have retired over a year ago, and don't even have a computer
anymore.
sean

**Comment by ivanove** [comment]
ok duude thank's
